services:
  mysql:
    image: mysql:8.0
    container_name: admission_mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admission_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: admission_adminer
    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - mysql

volumes:
  mysql_data: